#!/usr/bin/env zsh

OS="$(uname)"

case "${OS}" in
    Linux)
      # Sets fiio and HD600S2, if available, as default audio output. See zsh-aliases for `out-fiio`
	      out-fiio &>/dev/null

        BREW_BIN_PATH='/home/linuxbrew/.linuxbrew/bin'
        case ":$PATH:" in
          *":$BREW_BIN_PATH:"*) ;;
          *) 
            #Sets brew binary in $PATH
            eval "$($BREW_BIN_PATH/brew shellenv)"
            ;;
        esac
      ;;
    Darwin)
        # If on Apple Silicon, then path must be /opt/homebrew/bin/brew

        BREW_BIN_PATH='/usr/local/bin'
        case ":$PATH:" in
          *":$BREW_BIN_PATH:"*) ;;
          *) 
            eval "$($BREW_BIN_PATH/brew shellenv)"
            ;;
        esac

        alias firefox="/Applications/Firefox\ Developer\ Edition.app/Contents/MacOS/firefox"
      ;;

esac

# run file synching software we are not on WM i3
if ! pgrep i3 &>/dev/null; then
  nohup syncthing >/dev/null 2>&1 &
  disown
  echo "Running syncthing in the background"
fi

# must be loaded after initializing brew shellenv
# zoxide - a smarter cd command
eval "$(zoxide init zsh)"

[[ -x $HOME/.cargo/env ]] && ."${HOME}/.cargo/env"

# NVM - Node Version Manager
export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm
