#!usr/bin/env bash

# SASS
function sass-run() {

# sass app/scss:dist/ --style=compressed --watch

  local default_style="compressed"
  local source_dir=${1}
  local dist_dir=${2}

  echo "Running sass as 'sass ${source_dir}:${dist_dir} --style=compressed --watch'"

  echo "Check docs: https://sass-lang.com/documentation/cli/ruby-sass/"

  if ! command -v sass &>/dev/null;then
    echo "Command 'sass' not found"
  else
    sass "${source_dir}:${dist_dir}" --style=compressed --watch
  fi
  
}

# Tmux Layout
function ide() {
  #only allow numbers
  readonly VERTICAL_SPLIT=1
  case $1 in
    ''|*[!0-9]*) echo "Usage: ide <session_number>"; return 1;;
    *)
      echo "Creating tmux layout"
      for i in $(seq 1 $1); do
        if [ "$i" -eq $VERTICAL_SPLIT ]; then
          tmux split-window -v
          tmux resize-pane -y 16%
        else
          tmux split-window -h
        fi
      done

    ;;
  esac
}

function ccwd() {
  pwd | pbcopy
  echo "cwd copied to clipboard"
}

# Cheat sheet
# info http://cht.sh
#alias cheat="curl cheat.sh/ "
function cheat() {
  local _search="$1"

  curl cheat.sh/"${_search}"

}

function ts() {
  local _session="$1"

  tmux switch-client -t "${_session}"
}

function tka() {
  tmux kill-pane -a -t 0
}

function tk() {
  local _pane="$1"
  tmux kill-pane -t "${_pane}"
}

# Find current dir
function fcd() {
  local _search_string="$1"
  la | grep "${_search_string}"
}

# Find <word> in current files
function ff(){
  local _search_string="$1"
  ll | grep "^-" | awk -F ' ' '{print $NF}' | xargs grep -n "${_search_string}"
}

function git_init_custom() {
    git init "$@"
    printf "Currently git user.name set as: [%s] \n" $(git config --get user.name)
    printf "Currently git user.email set as: [%s] \n" $(git config --get user.email)
    printf "if you do not want to commit as such author: [%s]\n" $(git config --get user.email)
    printf "Consider changing --local user.name and --local user.email for this repo!!!\n"
}

# -0 Change xargs to expect NUL (``\0'') characters as separators, instead of spaces and newlines.  This is expected to be used in concert with the -print0 function in find(1).
# -print0 this primary always evaluates to true.  It prints the pathname of the current file to standard output, followed by an ASCII NUL character (character code 0).
alias zsh-update-plugins="find "$ZDOTDIR/plugins" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I dirpath -0 git -C dirpath pull -q"

# ls color output -G for osx and --color=auto for linux
ls --color=auto &> /dev/null && alias ll='ls --color=auto -hAlt' || alias ll='ls -GhAlt'

alias ls='eza --group-directories-first'
alias ll='eza -l --icons --group-directories-first --time-style long-iso'
alias la='eza -la -F=always --icons --group-directories-first --time-style long-iso'

# confirm before overwriting sm
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

# Colorize grep output (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'


# get top process eating memory
alias psmem='ps auxf | sort -nr -k 4 | head -5'

# get top process eating cpu ##
alias pscpu='ps auxf | sort -nr -k 3 | head -5'

# Get git aliases
alias gital='cat $ZDOTDIR/zsh-aliases | tail -21'

# Start Tmux with $XDG_CONFIG_HOME/tmux/*.tmux.conf
alias tm="tmux -f $XDG_CONFIG_HOME/tmux/.tmux.conf"

# Lazygit
alias lg="lazygit"

#pnpm
alias pn="pnpm"

alias luamake=/home/juanse/lua-language-server/3rd/luamake/luamake

# ----------------------
# Git Aliases
# ----------------------
alias gb='git branch -a'
alias gbd='git branch -d'
alias ga='git add'
alias gaa='git add .'
alias gaaa='git add -A'
alias gco='git checkout'
alias gcob='git checkout -b'
alias gc='git commit'
alias gcm='git commit -m'
alias gd='git diff'
alias gi='git_init_custom'
alias gl='git log --oneline --graph --color --all --decorate'
alias gp='git pull'
alias gpsh='git push'
alias gss='git status -s'
alias gs='echo ""; echo "*********************************************"; echo -e "   DO NOT FORGET TO PULL BEFORE COMMITTING"; echo "*********************************************"; echo ""; git status'
alias gr='git remote'
alias grv='git remote -v'

# ########## LINUX ONLY ALIAS ###############
# Change default audio output
# List avaialble devices running 'pactl list | grep "Monitor of Sink"'.
alias out-speakers='pactl set-default-sink alsa_output.pci-0000_2d_00.4.analog-stereo'
alias out-fiio='pactl set-default-sink alsa_output.usb-GuangZhou_FiiO_Electronics_Co._Ltd_FiiO_K7-00.analog-stereo'
alias out-nova='pactl set-default-sink alsa_output.usb-SteelSeries_Arctis_Nova_Pro_Wireless-00.analog-stereo'
