#!/usr/bin/env bash

# FZF must be installed through brew (https://brew.sh/)
#
# FZF key-bindings
#
# Preview file content using bat (https://github.com/sharkdp/bat)
export FZF_CTRL_T_OPTS="
  --preview 'bat -n --color=always {}'
  --bind 'ctrl-/:change-preview-window(down|hidden|)'"

# CTRL-/ to toggle small preview window to see the full command
# CTRL-Y to copy the command into clipboard using pbcopy
export FZF_CTRL_R_OPTS="
  --preview 'echo {}' --preview-window up:3:hidden:wrap
  --bind 'ctrl-/:toggle-preview'
  --bind 'ctrl-y:execute-silent(echo -n {2..} | pbcopy)+abort'
  --color header:italic
  --header 'Press CTRL-Y to copy command into clipboard'"

[ -f "${XDG_CONFIG_HOME:-$HOME/.config}"/fzf/key-bindings.zsh ] && source "${XDG_CONFIG_HOME:-$HOME/.config}"/fzf/key-bindings.zsh
